### ISSUE TITLE
pytest import Parser, but deprecated in pytest 6.00 or later

### ISSUE THREAD

**Issue by yudataguy** [ClearcodeHQ/pytest-rabbitmq#359]
### What action do you want to perform
Here's my simple test code:
```
from pytest_rabbitmq import factories

rabbitmq_my = factories.rabbitmq()

def test_send_and_consume(rabbitmq_my):
    test_message = {"rabbit": "white"}

    rabbitmq_my.publish_message(test_message)

    consumed_message = rabbitmq_my.consume_message()

    assert consumed_message == test_message
```

### What are the results
Getting error:
```
 from pytest import Parser
admin_platform-test_runner-1  | ImportError: cannot import name 'Parser' from 'pytest' (/usr/local/lib/python3.9/site-packages/pytest/__init__.py)
```

### What are the expected results
Not sure why ```Parser``` is used here,  i'm on 3.0.1

**Comment by fizyk** [comment]
@yudataguy the tests on CI here are running on pytest 7.4, and if I recall the pytest.Parser (along with many other types and main package level) was introduced in pytest 6.2. Since then the previous usage got deprecated.

Not sure how you install your dependencies, but pytest-rabbitmq 3 has strict requirement for pytest > 6.2, and judging from the issue title you're on pytest 6
